//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WallpaperChanger.Activities.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WallpaperChanger.Activities.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Authentication に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Authentication_Category {
            get {
                return ResourceManager.GetString("Authentication_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Change the wallpaper with the specified image file. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ChangeWallpaper_Description {
            get {
                return ResourceManager.GetString("ChangeWallpaper_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Change Wallpaper に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ChangeWallpaper_DisplayName {
            get {
                return ResourceManager.GetString("ChangeWallpaper_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Wallpaper image file に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ChangeWallpaper_ImageFilePath_Description {
            get {
                return ResourceManager.GetString("ChangeWallpaper_ImageFilePath_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ImageFilePath に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ChangeWallpaper_ImageFilePath_DisplayName {
            get {
                return ResourceManager.GetString("ChangeWallpaper_ImageFilePath_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Returns true if successful. If it fails, false will be returned. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ChangeWallpaper_Result_Description {
            get {
                return ResourceManager.GetString("ChangeWallpaper_Result_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Result に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ChangeWallpaper_Result_DisplayName {
            get {
                return ResourceManager.GetString("ChangeWallpaper_Result_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Common に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_Category {
            get {
                return ResourceManager.GetString("Common_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   If set, continue executing the remaining activities even if the current activity has failed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ContinueOnError_Description {
            get {
                return ResourceManager.GetString("ContinueOnError_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ContinueOnError に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ContinueOnError_DisplayName {
            get {
                return ResourceManager.GetString("ContinueOnError_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Do {
            get {
                return ResourceManager.GetString("Do", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GenerateWallpaper_BackGroundColor_Description {
            get {
                return ResourceManager.GetString("GenerateWallpaper_BackGroundColor_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   BackGroundColor に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GenerateWallpaper_BackGroundColor_DisplayName {
            get {
                return ResourceManager.GetString("GenerateWallpaper_BackGroundColor_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Create a wallpaper image file by specifying the background color and text. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GenerateWallpaper_Description {
            get {
                return ResourceManager.GetString("GenerateWallpaper_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Generate Wallpaper に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GenerateWallpaper_DisplayName {
            get {
                return ResourceManager.GetString("GenerateWallpaper_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GenerateWallpaper_FontName_Description {
            get {
                return ResourceManager.GetString("GenerateWallpaper_FontName_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FontName に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GenerateWallpaper_FontName_DisplayName {
            get {
                return ResourceManager.GetString("GenerateWallpaper_FontName_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GenerateWallpaper_FontSize_Description {
            get {
                return ResourceManager.GetString("GenerateWallpaper_FontSize_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FontSize に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GenerateWallpaper_FontSize_DisplayName {
            get {
                return ResourceManager.GetString("GenerateWallpaper_FontSize_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GenerateWallpaper_OutputFilePath_Description {
            get {
                return ResourceManager.GetString("GenerateWallpaper_OutputFilePath_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OutputFilePath に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GenerateWallpaper_OutputFilePath_DisplayName {
            get {
                return ResourceManager.GetString("GenerateWallpaper_OutputFilePath_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Returns true if successful. If it fails, false will be returned. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GenerateWallpaper_Result_Description {
            get {
                return ResourceManager.GetString("GenerateWallpaper_Result_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Result に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GenerateWallpaper_Result_DisplayName {
            get {
                return ResourceManager.GetString("GenerateWallpaper_Result_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GenerateWallpaper_Text_Description {
            get {
                return ResourceManager.GetString("GenerateWallpaper_Text_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Text に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GenerateWallpaper_Text_DisplayName {
            get {
                return ResourceManager.GetString("GenerateWallpaper_Text_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GenerateWallpaper_TextColor_Description {
            get {
                return ResourceManager.GetString("GenerateWallpaper_TextColor_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TextColor に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GenerateWallpaper_TextColor_DisplayName {
            get {
                return ResourceManager.GetString("GenerateWallpaper_TextColor_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Create a wallpaper image file by specifying the wallpaper image and text. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GenerateWallpaperWithImageFile_Description {
            get {
                return ResourceManager.GetString("GenerateWallpaperWithImageFile_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Generate Wallpaper With ImageFile に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GenerateWallpaperWithImageFile_DisplayName {
            get {
                return ResourceManager.GetString("GenerateWallpaperWithImageFile_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GenerateWallpaperWithImageFile_FontName_Description {
            get {
                return ResourceManager.GetString("GenerateWallpaperWithImageFile_FontName_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FontName に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GenerateWallpaperWithImageFile_FontName_DisplayName {
            get {
                return ResourceManager.GetString("GenerateWallpaperWithImageFile_FontName_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GenerateWallpaperWithImageFile_FontSize_Description {
            get {
                return ResourceManager.GetString("GenerateWallpaperWithImageFile_FontSize_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FontSize に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GenerateWallpaperWithImageFile_FontSize_DisplayName {
            get {
                return ResourceManager.GetString("GenerateWallpaperWithImageFile_FontSize_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GenerateWallpaperWithImageFile_ImageFilePath_Description {
            get {
                return ResourceManager.GetString("GenerateWallpaperWithImageFile_ImageFilePath_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ImageFilePath に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GenerateWallpaperWithImageFile_ImageFilePath_DisplayName {
            get {
                return ResourceManager.GetString("GenerateWallpaperWithImageFile_ImageFilePath_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GenerateWallpaperWithImageFile_OutputFilePath_Description {
            get {
                return ResourceManager.GetString("GenerateWallpaperWithImageFile_OutputFilePath_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OutputFilePath に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GenerateWallpaperWithImageFile_OutputFilePath_DisplayName {
            get {
                return ResourceManager.GetString("GenerateWallpaperWithImageFile_OutputFilePath_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Returns true if successful. If it fails, false will be returned. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GenerateWallpaperWithImageFile_Result_Description {
            get {
                return ResourceManager.GetString("GenerateWallpaperWithImageFile_Result_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Result に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GenerateWallpaperWithImageFile_Result_DisplayName {
            get {
                return ResourceManager.GetString("GenerateWallpaperWithImageFile_Result_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GenerateWallpaperWithImageFile_Text_Description {
            get {
                return ResourceManager.GetString("GenerateWallpaperWithImageFile_Text_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Text に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GenerateWallpaperWithImageFile_Text_DisplayName {
            get {
                return ResourceManager.GetString("GenerateWallpaperWithImageFile_Text_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GenerateWallpaperWithImageFile_TextColor_Description {
            get {
                return ResourceManager.GetString("GenerateWallpaperWithImageFile_TextColor_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TextColor に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GenerateWallpaperWithImageFile_TextColor_DisplayName {
            get {
                return ResourceManager.GetString("GenerateWallpaperWithImageFile_TextColor_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Input に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Input_Category {
            get {
                return ResourceManager.GetString("Input_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Options に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Options_Category {
            get {
                return ResourceManager.GetString("Options_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Output に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Output_Category {
            get {
                return ResourceManager.GetString("Output_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Specifies the amount of time (in milliseconds) to wait for the activity to run before an error is thrown. The default value is 60000 (1 minute). に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Timeout_Description {
            get {
                return ResourceManager.GetString("Timeout_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Timeout (milliseconds) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Timeout_DisplayName {
            get {
                return ResourceManager.GetString("Timeout_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The activity timed out and was canceled. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Timeout_Error {
            get {
                return ResourceManager.GetString("Timeout_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please provide a value either for {0} or {1}, but not both. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ValidationExclusiveProperties_Error {
            get {
                return ResourceManager.GetString("ValidationExclusiveProperties_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please provide values for both {0} and {1}. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ValidationOverloadGroup_Error {
            get {
                return ResourceManager.GetString("ValidationOverloadGroup_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cannot be used outside of a {0}. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ValidationScope_Error {
            get {
                return ResourceManager.GetString("ValidationScope_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please provide a value for {0}. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ValidationValue_Error {
            get {
                return ResourceManager.GetString("ValidationValue_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please input existing full path for {0}. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ValidationValueFullPath_Error {
            get {
                return ResourceManager.GetString("ValidationValueFullPath_Error", resourceCulture);
            }
        }
    }
}
